services:
  - type: static
    name: bookshaven-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    headers:
      - path: "/**/*.js"
        headers:
          - key: Content-Type
            value: application/javascript; charset=utf-8
      - path: "/**/*.mjs"
        headers:
          - key: Content-Type
            value: application/javascript
      - path: "/**/*.css"
        headers:
          - key: Content-Type
            value: text/css; charset=utf-8
    routes:
      - path: "/*"
        destination: "/index.html"
        statusCode: 200