# Generated by Django 5.2.12 on 2026-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_available_copies_book_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
