# Generated by Django 6.0.3 on 2026-03-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Upload a book cover image (JPG, PNG, etc.)', null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Children', 'Children'), ('Young Adult', 'Young Adult'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Self-Help', 'Self-Help'), ('Business', 'Business'), ('Technology', 'Technology'), ('Art & Design', 'Art & Design'), ('Cooking', 'Cooking'), ('Sports', 'Sports'), ('Travel', 'Travel'), ('Education', 'Education'), ('Philosophy', 'Philosophy'), ('Psychology', 'Psychology'), ('Religion', 'Religion'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
