# Generated by Django 6.0.3 on 2026-03-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
