# Generated by Django 6.0.3 on 2026-03-17 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'return_date'], name='books_loan_user_id_43503c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', '-borrow_date'], name='books_loan_user_id_419889_idx'),
        ),
    ]
